### ISSUE TITLE
How to run Teku DAS with Kurtosis suite

### ISSUE THREAD

**Issue by zilm13** [Nashatyrev/artemis#30]
1. Install Kurtosis ([Documentation](https://github.com/kurtosis-tech/ethereum-package), [Quick install](https://docs.kurtosis.com/install/))
2. Patch your local Teku with something like this: https://github.com/zilm13/teku/commit/e38b353f93e8d75a3695bf58f7fb97f28c1a0d1b (mimic deneb in restAPI, hardcode config yaml constants, preset constants not needed, will be wired up)
3. Run `./gradlew distDocker` in Teku repository to cache it locally as `consensys/teku:develop`
4. Create your Kurtosis config. Something like this, say it's called `das.yaml`:
```yaml
participants:
  - el_type: geth
    el_max_cpu: 2000
    el_max_mem: 2000
    cl_type: teku
    cl_image: consensys/teku:develop
    cl_extra_params:
      - "--Xnetwork-das-fork-epoch=1"    
    count: 1
network_params:
    deneb_fork_epoch: 0
    preset: "minimal"    
additional_services:
  - el_forkmon
  - tx_spammer
  - blob_spammer
  - dora
snooper_enabled: true
```
Some notes about it:
 - I see issues with geth missing execution payload often with default settings, so added cpu and mem, defaults are `1000` and `1000`
 - We start DAS at epoch 1, first is deneb. Only CL thinks that it's another fork, EIP7594, EL still works as usual on Deneb
 - Increase count if you need several CL-EL pairs
 - `blob_spammer` will include blobs in execution payload
 5. Run enclave in Kurtosis:
 ```bash
 kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package --args-file ./das.yaml

 ```
 After command completes, type `kurtosis web` to check how it goes.
 Another quick notes:
 - to shutdown enclave: `kurtosis enclave rm -f my-testnet`
 - from web access `dora`  web, it's a block explorer. It doesn't contain any blobs info, but you could check it in CL logs
 - I've not tried to use blobscan is it should be useless in EIP-7594, because it's designed for Deneb
 - access something like `cl-1-teku-geth` -> `Logs` from web panel to view Teku logs

 TODO:
 - several pairs startup with predefined p2p private key for fixed subnets and extra_subnets, so they cover all columns
